export const listAccount = [
  {
    admin: {
      username: "admin",
      password: "admin",
      email: "admin@example.com",
      role: "admin",
      fullName: "Admin User",
    },
    users: [
      {
        username: "user",
        password: "user",
        email: "user@example.com",
        role: "user",
        fullName: "User One",
      },
    ],
  },
];
export const sidebar = [
  {
    id: 1,
    title: "MAIN",
    listItems: [
      {
        id: 1,
        title: "Homepage",
        url: "/",
        icon: "/home.svg",
      },
    ],
  },
  {
    id: 2,
    title: "ADMIN",
    listItems: [
      {
        id: 1,
        title: "Dashboard",
        url: "/admin",
        icon: "/home.svg",
      },
      {
        id: 2,
        title: "Profiles",
        url: "/admin/users",
        icon: "/user.svg",
      },
      {
        id: 3,
        title: "Actual Data",
        url: "/admin/actualData",
        icon: "/chart.svg",
      },
      {
        id: 4,
        title: "Reservation Forecast",
        url: "/admin/reservationForecast",
        icon: "/post.svg",
      },
      {
        id: 5,
        title: "Period Detail",
        url: "/admin/periodDetail",
        icon: "/form.svg",
      },
    ],
  },
];
export const HotelData = [
  {
    actualData: [
      {
        id: 1,
        property: "SPH1",
        totalRoomInHotel: 744,
        roomRevenue: "$234,458.70",
        FBRevenue: "$609,316.22",
        otherRevenue: "$51,547.30",
        totalRevenue: "$895,322.22",
        occPercentage: "22.80%",
        ADR: "$57.59",
        hotelRoom: 17856,
        availableRooms: 13785,
        occupiedRoom: "$234,458.70",
        groupRooms: "$145,896.90",
        transientRooms: "$88,561.79",
        occupiedRoomPercentage: "22.8%",
        groupRoomPercentage: "14.0%",
        transientRoomPercentage: "8.8%",
      },
      {
        id: 2,
        property: "SPH2",
        totalRoomInHotel: 744,
        roomRevenue: "$234,458.70",
        FBRevenue: "$609,316.22",
        otherRevenue: "$51,547.30",
        totalRevenue: "$895,322.22",
        occPercentage: "22.80%",
        ADR: "$57.59",
        hotelRoom: 17856,
        availableRooms: 13785,
        occupiedRoom: "$234,458.70",
        groupRooms: "$145,896.90",
        transientRooms: "$88,561.79",
        occupiedRoomPercentage: "22.8%",
        groupRoomPercentage: "14.0%",
        transientRoomPercentage: "8.8%",
      },
      {
        id: 3,
        property: "SPH3",
        totalRoomInHotel: 744,
        roomRevenue: "$234,458.70",
        FBRevenue: "$609,316.22",
        otherRevenue: "$51,547.30",
        totalRevenue: "$895,322.22",
        occPercentage: "22.80%",
        ADR: "$57.59",
        hotelRoom: 17856,
        availableRooms: 13785,
        occupiedRoom: "$234,458.70",
        groupRooms: "$145,896.90",
        transientRooms: "$88,561.79",
        occupiedRoomPercentage: "22.8%",
        groupRoomPercentage: "14.0%",
        transientRoomPercentage: "8.8%",
      },
    ],
  },

  {
    reservationForecastMonth: [
      {
        from_date: "01-Feb-2020",
        to_date: "29-Feb-2020",
        total: {
          "No of Day": 29,
          Rooms: 4308,
          "Total Room": 21576,
          "Occ %": "20%",
          "Total Revenue": 245664.56,
        },
        outlet: [
          {
            date: "01-Feb-2020",
            "Total Occ.": 166,
            "Arr. Rooms": 109,
            "Dep. Rooms": 66,
            "Room Revenue": 11396,
            "Average Rate": 69,
            "Day Use Rooms": 2,
            "No Show Rooms": 0,
            "Adl. & Chl.": 303,
          },
          {
            date: "02-Feb-2020",
            "Total Occ.": 172,
            "Arr. Rooms": 91,
            "Dep. Rooms": 85,
            "Room Revenue": 11786,
            "Average Rate": 69,
            "Day Use Rooms": 2,
            "No Show Rooms": 0,
            "Adl. & Chl.": 283,
          },
          {
            date: "03-Feb-2020",
            "Total Occ.": 132,
            "Arr. Rooms": 77,
            "Dep. Rooms": 117,
            "Room Revenue": 7260,
            "Average Rate": 55,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 190,
          },
          {
            date: "04-Feb-2020",
            "Total Occ.": 118,
            "Arr. Rooms": 56,
            "Dep. Rooms": 70,
            "Room Revenue": 6208,
            "Average Rate": 53,
            "Day Use Rooms": 4,
            "No Show Rooms": 0,
            "Adl. & Chl.": 172,
          },
          {
            date: "05-Feb-2020",
            "Total Occ.": 103,
            "Arr. Rooms": 75,
            "Dep. Rooms": 90,
            "Room Revenue": 6208,
            "Average Rate": 60,
            "Day Use Rooms": 8,
            "No Show Rooms": 0,
            "Adl. & Chl.": 152,
          },
          {
            date: "06-Feb-2020",
            "Total Occ.": 100,
            "Arr. Rooms": 54,
            "Dep. Rooms": 57,
            "Room Revenue": 5399,
            "Average Rate": 54,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 144,
          },
          {
            date: "07-Feb-2020",
            "Total Occ.": 116,
            "Arr. Rooms": 58,
            "Dep. Rooms": 42,
            "Room Revenue": 6193,
            "Average Rate": 53,
            "Day Use Rooms": 3,
            "No Show Rooms": 0,
            "Adl. & Chl.": 179,
          },
          {
            date: "08-Feb-2020",
            "Total Occ.": 112,
            "Arr. Rooms": 80,
            "Dep. Rooms": 84,
            "Room Revenue": 5536,
            "Average Rate": 49,
            "Day Use Rooms": 0,
            "No Show Rooms": 1,
            "Adl. & Chl.": 173,
          },
          {
            date: "09-Feb-2020",
            "Total Occ.": 94,
            "Arr. Rooms": 46,
            "Dep. Rooms": 64,
            "Room Revenue": 4975,
            "Average Rate": 53,
            "Day Use Rooms": 4,
            "No Show Rooms": 0,
            "Adl. & Chl.": 130,
          },
          {
            date: "10-Feb-2020",
            "Total Occ.": 88,
            "Arr. Rooms": 42,
            "Dep. Rooms": 48,
            "Room Revenue": 4566,
            "Average Rate": 52,
            "Day Use Rooms": 1,
            "No Show Rooms": 0,
            "Adl. & Chl.": 121,
          },
          {
            date: "11-Feb-2020",
            "Total Occ.": 104,
            "Arr. Rooms": 61,
            "Dep. Rooms": 45,
            "Room Revenue": 5706,
            "Average Rate": 55,
            "Day Use Rooms": 1,
            "No Show Rooms": 1,
            "Adl. & Chl.": 151,
          },
          {
            date: "12-Feb-2020",
            "Total Occ.": 122,
            "Arr. Rooms": 77,
            "Dep. Rooms": 59,
            "Room Revenue": 6359,
            "Average Rate": 52,
            "Day Use Rooms": 1,
            "No Show Rooms": 1,
            "Adl. & Chl.": 180,
          },
          {
            date: "13-Feb-2020",
            "Total Occ.": 136,
            "Arr. Rooms": 80,
            "Dep. Rooms": 66,
            "Room Revenue": 6830,
            "Average Rate": 50,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 206,
          },
          {
            date: "14-Feb-2020",
            "Total Occ.": 139,
            "Arr. Rooms": 88,
            "Dep. Rooms": 85,
            "Room Revenue": 7242,
            "Average Rate": 52,
            "Day Use Rooms": 2,
            "No Show Rooms": 4,
            "Adl. & Chl.": 213,
          },
          {
            date: "15-Feb-2020",
            "Total Occ.": 439,
            "Arr. Rooms": 412,
            "Dep. Rooms": 111,
            "Room Revenue": 23903,
            "Average Rate": 54,
            "Day Use Rooms": 18,
            "No Show Rooms": 0,
            "Adl. & Chl.": 794,
          },
          {
            date: "16-Feb-2020",
            "Total Occ.": 377,
            "Arr. Rooms": 46,
            "Dep. Rooms": 108,
            "Room Revenue": 20117,
            "Average Rate": 53,
            "Day Use Rooms": 1,
            "No Show Rooms": 2,
            "Adl. & Chl.": 677,
          },
          {
            date: "17-Feb-2020",
            "Total Occ.": 357,
            "Arr. Rooms": 41,
            "Dep. Rooms": 61,
            "Room Revenue": 19177,
            "Average Rate": 54,
            "Day Use Rooms": 1,
            "No Show Rooms": 0,
            "Adl. & Chl.": 648,
          },
          {
            date: "18-Feb-2020",
            "Total Occ.": 330,
            "Arr. Rooms": 21,
            "Dep. Rooms": 48,
            "Room Revenue": 19094,
            "Average Rate": 58,
            "Day Use Rooms": 2,
            "No Show Rooms": 0,
            "Adl. & Chl.": 609,
          },
          {
            date: "19-Feb-2020",
            "Total Occ.": 403,
            "Arr. Rooms": 167,
            "Dep. Rooms": 94,
            "Room Revenue": 24392,
            "Average Rate": 61,
            "Day Use Rooms": 0,
            "No Show Rooms": 2,
            "Adl. & Chl.": 698,
          },
          {
            date: "20-Feb-2020",
            "Total Occ.": 166,
            "Arr. Rooms": 31,
            "Dep. Rooms": 267,
            "Room Revenue": 11786,
            "Average Rate": 71,
            "Day Use Rooms": 0,
            "No Show Rooms": 3,
            "Adl. & Chl.": 275,
          },
          {
            date: "21-Feb-2020",
            "Total Occ.": 115,
            "Arr. Rooms": 54,
            "Dep. Rooms": 105,
            "Room Revenue": 10154,
            "Average Rate": 88,
            "Day Use Rooms": 7,
            "No Show Rooms": 1,
            "Adl. & Chl.": 179,
          },
          {
            date: "22-Feb-2020",
            "Total Occ.": 80,
            "Arr. Rooms": 32,
            "Dep. Rooms": 67,
            "Room Revenue": 5406,
            "Average Rate": 68,
            "Day Use Rooms": 1,
            "No Show Rooms": 0,
            "Adl. & Chl.": 134,
          },
          {
            date: "23-Feb-2020",
            "Total Occ.": 56,
            "Arr. Rooms": 17,
            "Dep. Rooms": 41,
            "Room Revenue": 3869,
            "Average Rate": 69,
            "Day Use Rooms": 1,
            "No Show Rooms": 1,
            "Adl. & Chl.": 84,
          },
          {
            date: "24-Feb-2020",
            "Total Occ.": 46,
            "Arr. Rooms": 17,
            "Dep. Rooms": 27,
            "Room Revenue": 895,
            "Average Rate": 19,
            "Day Use Rooms": 3,
            "No Show Rooms": 0,
            "Adl. & Chl.": 65,
          },
          {
            date: "25-Feb-2020",
            "Total Occ.": 43,
            "Arr. Rooms": 8,
            "Dep. Rooms": 11,
            "Room Revenue": 2226,
            "Average Rate": 52,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 57,
          },
          {
            date: "26-Feb-2020",
            "Total Occ.": 79,
            "Arr. Rooms": 43,
            "Dep. Rooms": 7,
            "Room Revenue": 3901,
            "Average Rate": 49,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 120,
          },
          {
            date: "27-Feb-2020",
            "Total Occ.": 44,
            "Arr. Rooms": 1,
            "Dep. Rooms": 46,
            "Room Revenue": 2039,
            "Average Rate": 46,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 56,
          },
          {
            date: "28-Feb-2020",
            "Total Occ.": 44,
            "Arr. Rooms": 11,
            "Dep. Rooms": 5,
            "Room Revenue": 2053,
            "Average Rate": 47,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 57,
          },
          {
            date: "29-Feb-2020",
            "Total Occ.": 27,
            "Arr. Rooms": 3,
            "Dep. Rooms": 18,
            "Room Revenue": 987,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 37,
          },
        ],
      },
      {
        from_date: "01-Mar-2020",
        to_date: "31-Mar-2020",
        total: {
          "No of Day": 31,
          Rooms: 1490,
          "Total Room": 23064,
          "Occ %": "6%",
          "Total Revenue": 69382.74,
        },
        outlet: [
          {
            date: "01-Mar-2020",
            "Total Occ.": 47,
            "Arr. Rooms": 2,
            "Dep. Rooms": 5,
            "Room Revenue": 1696,
            "Average Rate": 36,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 56,
          },
          {
            date: "02-Mar-2020",
            "Total Occ.": 49,
            "Arr. Rooms": 3,
            "Dep. Rooms": 5,
            "Room Revenue": 2139,
            "Average Rate": 44,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 58,
          },
          {
            date: "03-Mar-2020",
            "Total Occ.": 56,
            "Arr. Rooms": 4,
            "Dep. Rooms": 0,
            "Room Revenue": 2483,
            "Average Rate": 44,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 68,
          },
          {
            date: "04-Mar-2020",
            "Total Occ.": 44,
            "Arr. Rooms": 0,
            "Dep. Rooms": 3,
            "Room Revenue": 1661,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 53,
          },
          {
            date: "05-Mar-2020",
            "Total Occ.": 34,
            "Arr. Rooms": 1,
            "Dep. Rooms": 3,
            "Room Revenue": 1147,
            "Average Rate": 34,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 42,
          },
          {
            date: "06-Mar-2020",
            "Total Occ.": 38,
            "Arr. Rooms": 2,
            "Dep. Rooms": 2,
            "Room Revenue": 1366,
            "Average Rate": 36,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 45,
          },
          {
            date: "07-Mar-2020",
            "Total Occ.": 37,
            "Arr. Rooms": 3,
            "Dep. Rooms": 2,
            "Room Revenue": 1378,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 46,
          },
          {
            date: "08-Mar-2020",
            "Total Occ.": 37,
            "Arr. Rooms": 4,
            "Dep. Rooms": 2,
            "Room Revenue": 1444,
            "Average Rate": 39,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 48,
          },
          {
            date: "09-Mar-2020",
            "Total Occ.": 37,
            "Arr. Rooms": 3,
            "Dep. Rooms": 6,
            "Room Revenue": 1588,
            "Average Rate": 43,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 45,
          },
          {
            date: "10-Mar-2020",
            "Total Occ.": 37,
            "Arr. Rooms": 5,
            "Dep. Rooms": 2,
            "Room Revenue": 1765,
            "Average Rate": 48,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 46,
          },
          {
            date: "11-Mar-2020",
            "Total Occ.": 46,
            "Arr. Rooms": 1,
            "Dep. Rooms": 4,
            "Room Revenue": 2103,
            "Average Rate": 46,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 49,
          },
          {
            date: "12-Mar-2020",
            "Total Occ.": 36,
            "Arr. Rooms": 0,
            "Dep. Rooms": 6,
            "Room Revenue": 1536,
            "Average Rate": 43,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 36,
          },
          {
            date: "13-Mar-2020",
            "Total Occ.": 46,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 1680,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 46,
          },
          {
            date: "14-Mar-2020",
            "Total Occ.": 30,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1007,
            "Average Rate": 34,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 30,
          },
          {
            date: "15-Mar-2020",
            "Total Occ.": 33,
            "Arr. Rooms": 1,
            "Dep. Rooms": 1,
            "Room Revenue": 1323,
            "Average Rate": 40,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 34,
          },
          {
            date: "16-Mar-2020",
            "Total Occ.": 40,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 1597,
            "Average Rate": 40,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 40,
          },
          {
            date: "17-Mar-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 880,
            "Average Rate": 34,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 26,
          },
          {
            date: "18-Mar-2020",
            "Total Occ.": 40,
            "Arr. Rooms": 9,
            "Dep. Rooms": 0,
            "Room Revenue": 1735,
            "Average Rate": 43,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 47,
          },
          {
            date: "19-Mar-2020",
            "Total Occ.": 48,
            "Arr. Rooms": 1,
            "Dep. Rooms": 1,
            "Room Revenue": 2231,
            "Average Rate": 46,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 56,
          },
          {
            date: "20-Mar-2020",
            "Total Occ.": 76,
            "Arr. Rooms": 3,
            "Dep. Rooms": 1,
            "Room Revenue": 3666,
            "Average Rate": 48,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 85,
          },
          {
            date: "21-Mar-2020",
            "Total Occ.": 37,
            "Arr. Rooms": 1,
            "Dep. Rooms": 2,
            "Room Revenue": 1613,
            "Average Rate": 44,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 47,
          },
          {
            date: "22-Mar-2020",
            "Total Occ.": 28,
            "Arr. Rooms": 2,
            "Dep. Rooms": 10,
            "Room Revenue": 962,
            "Average Rate": 34,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 29,
          },
          {
            date: "23-Mar-2020",
            "Total Occ.": 57,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 2798,
            "Average Rate": 49,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 58,
          },
          {
            date: "24-Mar-2020",
            "Total Occ.": 227,
            "Arr. Rooms": 1,
            "Dep. Rooms": 1,
            "Room Revenue": 15304,
            "Average Rate": 67,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 227,
          },
          {
            date: "25-Mar-2020",
            "Total Occ.": 55,
            "Arr. Rooms": 2,
            "Dep. Rooms": 2,
            "Room Revenue": 2450,
            "Average Rate": 45,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 56,
          },
          {
            date: "26-Mar-2020",
            "Total Occ.": 44,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 1695,
            "Average Rate": 39,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 44,
          },
          {
            date: "27-Mar-2020",
            "Total Occ.": 37,
            "Arr. Rooms": 2,
            "Dep. Rooms": 1,
            "Room Revenue": 1429,
            "Average Rate": 39,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 38,
          },
          {
            date: "28-Mar-2020",
            "Total Occ.": 31,
            "Arr. Rooms": 0,
            "Dep. Rooms": 2,
            "Room Revenue": 1126,
            "Average Rate": 36,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 31,
          },
          {
            date: "29-Mar-2020",
            "Total Occ.": 44,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1928,
            "Average Rate": 44,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 44,
          },
          {
            date: "30-Mar-2020",
            "Total Occ.": 50,
            "Arr. Rooms": 2,
            "Dep. Rooms": 0,
            "Room Revenue": 3767,
            "Average Rate": 75,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 52,
          },
          {
            date: "31-Mar-2020",
            "Total Occ.": 43,
            "Arr. Rooms": 0,
            "Dep. Rooms": 2,
            "Room Revenue": 1885,
            "Average Rate": 44,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 43,
          },
        ],
      },
      {
        from_date: "01-Apr-2020",
        to_date: "30-Apr-2020",
        total: {
          "No of Day": 30,
          Rooms: 1007,
          "Total Room": 22320,
          "Occ %": "5%",
          "Total Revenue": 39312.42,
        },
        outlet: [
          {
            date: "01-Apr-2020",
            "Total Occ.": 31,
            "Arr. Rooms": 1,
            "Dep. Rooms": 0,
            "Room Revenue": 1140,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 32,
          },
          {
            date: "02-Apr-2020",
            "Total Occ.": 36,
            "Arr. Rooms": 1,
            "Dep. Rooms": 1,
            "Room Revenue": 1536,
            "Average Rate": 43,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 36,
          },
          {
            date: "03-Apr-2020",
            "Total Occ.": 34,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1240,
            "Average Rate": 36,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 34,
          },

          {
            date: "03-Apr-2020",
            "Total Occ.": 34,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1240,
            "Average Rate": 36,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 34,
          },
          {
            date: "04-Apr-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 903,
            "Average Rate": 35,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 26,
          },
          {
            date: "05-Apr-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 1,
            "Dep. Rooms": 1,
            "Room Revenue": 902,
            "Average Rate": 35,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 27,
          },
          {
            date: "06-Apr-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 902,
            "Average Rate": 35,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 27,
          },
          {
            date: "07-Apr-2020",
            "Total Occ.": 25,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 844,
            "Average Rate": 34,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 25,
          },
          {
            date: "08-Apr-2020",
            "Total Occ.": 46,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 2152,
            "Average Rate": 47,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 46,
          },
          {
            date: "09-Apr-2020",
            "Total Occ.": 24,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 844,
            "Average Rate": 35,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 24,
          },
          {
            date: "10-Apr-2020",
            "Total Occ.": 30,
            "Arr. Rooms": 1,
            "Dep. Rooms": 0,
            "Room Revenue": 1113,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 31,
          },
          {
            date: "11-Apr-2020",
            "Total Occ.": 33,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1239,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 34,
          },
          {
            date: "12-Apr-2020",
            "Total Occ.": 25,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 902,
            "Average Rate": 36,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 26,
          },
          {
            date: "13-Apr-2020",
            "Total Occ.": 41,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 1920,
            "Average Rate": 47,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 41,
          },
          {
            date: "14-Apr-2020",
            "Total Occ.": 43,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1349,
            "Average Rate": 31,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 43,
          },
          {
            date: "15-Apr-2020",
            "Total Occ.": 37,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1612,
            "Average Rate": 44,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 37,
          },
          {
            date: "16-Apr-2020",
            "Total Occ.": 24,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 844,
            "Average Rate": 35,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 24,
          },
          {
            date: "17-Apr-2020",
            "Total Occ.": 29,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1054,
            "Average Rate": 36,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 29,
          },
          {
            date: "18-Apr-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 2,
            "Dep. Rooms": 0,
            "Room Revenue": 978,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 29,
          },
          {
            date: "19-Apr-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 2,
            "Dep. Rooms": 2,
            "Room Revenue": 953,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 28,
          },
          {
            date: "20-Apr-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 953,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 28,
          },
          {
            date: "21-Apr-2020",
            "Total Occ.": 24,
            "Arr. Rooms": 0,
            "Dep. Rooms": 2,
            "Room Revenue": 844,
            "Average Rate": 35,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 24,
          },
          {
            date: "22-Apr-2020",
            "Total Occ.": 62,
            "Arr. Rooms": 1,
            "Dep. Rooms": 1,
            "Room Revenue": 2005,
            "Average Rate": 32,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 62,
          },
          {
            date: "23-Apr-2020",
            "Total Occ.": 51,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 2448,
            "Average Rate": 48,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 51,
          },
          {
            date: "24-Apr-2020",
            "Total Occ.": 24,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 845,
            "Average Rate": 35,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 24,
          },
          {
            date: "25-Apr-2020",
            "Total Occ.": 36,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1350,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 36,
          },
          {
            date: "26-Apr-2020",
            "Total Occ.": 29,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1055,
            "Average Rate": 36,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 29,
          },
          {
            date: "27-Apr-2020",
            "Total Occ.": 32,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1181,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 32,
          },
          {
            date: "28-Apr-2020",
            "Total Occ.": 32,
            "Arr. Rooms": 3,
            "Dep. Rooms": 0,
            "Room Revenue": 1220,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 35,
          },
          {
            date: "29-Apr-2020",
            "Total Occ.": 54,
            "Arr. Rooms": 2,
            "Dep. Rooms": 0,
            "Room Revenue": 2708,
            "Average Rate": 50,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 59,
          },
          {
            date: "30-Apr-2020",
            "Total Occ.": 49,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 2277,
            "Average Rate": 46,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 54,
          },
        ],
      },
      {
        from_date: "01-May-2020",
        to_date: "31-May-2020",
        total: {
          "No of Day": 31,
          Rooms: 926,
          "Total Room": 23064,
          "Occ %": "4%",
          "Total Revenue": 38545.34,
        },
        outlet: [
          {
            date: "01-May-2020",
            "Total Occ.": 37,
            "Arr. Rooms": 0,
            "Dep. Rooms": 4,
            "Room Revenue": 1454,
            "Average Rate": 39,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 38,
          },
          {
            date: "02-May-2020",
            "Total Occ.": 41,
            "Arr. Rooms": 1,
            "Dep. Rooms": 2,
            "Room Revenue": 1602,
            "Average Rate": 39,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 42,
          },
          {
            date: "03-May-2020",
            "Total Occ.": 35,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 1320,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 35,
          },
          {
            date: "04-May-2020",
            "Total Occ.": 38,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1566,
            "Average Rate": 41,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 38,
          },
          {
            date: "05-May-2020",
            "Total Occ.": 54,
            "Arr. Rooms": 4,
            "Dep. Rooms": 0,
            "Room Revenue": 2545,
            "Average Rate": 47,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 54,
          },
          {
            date: "06-May-2020",
            "Total Occ.": 60,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 2899,
            "Average Rate": 48,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 60,
          },
          {
            date: "07-May-2020",
            "Total Occ.": 34,
            "Arr. Rooms": 2,
            "Dep. Rooms": 0,
            "Room Revenue": 1609,
            "Average Rate": 47,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 36,
          },
          {
            date: "08-May-2020",
            "Total Occ.": 36,
            "Arr. Rooms": 2,
            "Dep. Rooms": 3,
            "Room Revenue": 1739,
            "Average Rate": 48,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 38,
          },
          {
            date: "09-May-2020",
            "Total Occ.": 33,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1613,
            "Average Rate": 49,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 35,
          },
          {
            date: "10-May-2020",
            "Total Occ.": 22,
            "Arr. Rooms": 0,
            "Dep. Rooms": 6,
            "Room Revenue": 815,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 22,
          },
          {
            date: "11-May-2020",
            "Total Occ.": 29,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1229,
            "Average Rate": 42,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 29,
          },
          {
            date: "12-May-2020",
            "Total Occ.": 29,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1229,
            "Average Rate": 42,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 29,
          },
          {
            date: "13-May-2020",
            "Total Occ.": 22,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 815,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 22,
          },
          {
            date: "14-May-2020",
            "Total Occ.": 40,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1794,
            "Average Rate": 45,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 40,
          },
          {
            date: "15-May-2020",
            "Total Occ.": 22,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 815,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 22,
          },
          {
            date: "16-May-2020",
            "Total Occ.": 22,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 815,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 22,
          },
          {
            date: "17-May-2020",
            "Total Occ.": 22,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 815,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 22,
          },
          {
            date: "18-May-2020",
            "Total Occ.": 22,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 815,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 22,
          },
          {
            date: "19-May-2020",
            "Total Occ.": 22,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 815,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 22,
          },
          {
            date: "20-May-2020",
            "Total Occ.": 30,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1152,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 30,
          },
          {
            date: "21-May-2020",
            "Total Occ.": 27,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1026,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 27,
          },
          {
            date: "22-May-2020",
            "Total Occ.": 23,
            "Arr. Rooms": 2,
            "Dep. Rooms": 1,
            "Room Revenue": 897,
            "Average Rate": 39,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 25,
          },
          {
            date: "23-May-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 0,
            "Dep. Rooms": 2,
            "Room Revenue": 999,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 26,
          },
          {
            date: "24-May-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 788,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "25-May-2020",
            "Total Occ.": 28,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1202,
            "Average Rate": 43,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 28,
          },
          {
            date: "26-May-2020",
            "Total Occ.": 28,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1202,
            "Average Rate": 43,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 28,
          },
          {
            date: "27-May-2020",
            "Total Occ.": 34,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1611,
            "Average Rate": 47,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 34,
          },
          {
            date: "28-May-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 999,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 26,
          },
          {
            date: "29-May-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 788,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "30-May-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 788,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "31-May-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 787,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
        ],
      },
      {
        from_date: "01-Jun-2020",
        to_date: "30-Jun-2020",
        total: {
          "No of Day": 30,
          Rooms: 663,
          "Total Room": 22320,
          "Occ %": "3%",
          "Total Revenue": 22824.52,
        },
        outlet: [
          {
            date: "01-Jun-2020",
            "Total Occ.": 28,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1203,
            "Average Rate": 43,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 28,
          },
          {
            date: "02-Jun-2020",
            "Total Occ.": 28,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1203,
            "Average Rate": 43,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 28,
          },
          {
            date: "03-Jun-2020",
            "Total Occ.": 34,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1558,
            "Average Rate": 46,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 34,
          },
          {
            date: "04-Jun-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1000,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 26,
          },
          {
            date: "05-Jun-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 790,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "06-Jun-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1000,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 26,
          },
          {
            date: "07-Jun-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 790,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "08-Jun-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 790,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "09-Jun-2020",
            "Total Occ.": 54,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 790,
            "Average Rate": 15,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 54,
          },
          {
            date: "10-Jun-2020",
            "Total Occ.": 67,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1558,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 67,
          },
          {
            date: "11-Jun-2020",
            "Total Occ.": 59,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1000,
            "Average Rate": 17,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 59,
          },
          {
            date: "12-Jun-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 790,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "13-Jun-2020",
            "Total Occ.": 26,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1000,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 26,
          },
          {
            date: "14-Jun-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 790,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "15-Jun-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 790,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "16-Jun-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 790,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "17-Jun-2020",
            "Total Occ.": 39,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1768,
            "Average Rate": 45,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 39,
          },
          {
            date: "18-Jun-2020",
            "Total Occ.": 46,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 2266,
            "Average Rate": 49,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 46,
          },
          {
            date: "19-Jun-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 790,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "20-Jun-2020",
            "Total Occ.": 4,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 103,
            "Average Rate": 26,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 4,
          },
          {
            date: "21-Jun-2020",
            "Total Occ.": 4,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 103,
            "Average Rate": 26,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 4,
          },
          {
            date: "22-Jun-2020",
            "Total Occ.": 4,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 103,
            "Average Rate": 26,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 4,
          },
          {
            date: "23-Jun-2020",
            "Total Occ.": 4,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 103,
            "Average Rate": 26,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 4,
          },
          {
            date: "24-Jun-2020",
            "Total Occ.": 17,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 926,
            "Average Rate": 54,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 17,
          },
          {
            date: "25-Jun-2020",
            "Total Occ.": 9,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 313,
            "Average Rate": 35,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 9,
          },
          {
            date: "26-Jun-2020",
            "Total Occ.": 4,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 103,
            "Average Rate": 26,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 4,
          },
          {
            date: "27-Jun-2020",
            "Total Occ.": 4,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 103,
            "Average Rate": 26,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 4,
          },
          {
            date: "28-Jun-2020",
            "Total Occ.": 4,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 103,
            "Average Rate": 26,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 4,
          },
          {
            date: "29-Jun-2020",
            "Total Occ.": 4,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 103,
            "Average Rate": 26,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 4,
          },
          {
            date: "30-Jun-2020",
            "Total Occ.": 4,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 103,
            "Average Rate": 26,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 4,
          },
        ],
      },
      {
        from_date: "01-Jul-2020",
        to_date: "31-Jul-2020",
        total: {
          "No of Day": 31,
          Rooms: 664,
          "Total Room": 23064,
          "Occ %": "3%",
          "Total Revenue": 61867.87,
        },
        outlet: [
          {
            date: "01-Jul-2020",
            "Total Occ.": 29,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1375,
            "Average Rate": 47,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 29,
          },
          {
            date: "02-Jul-2020",
            "Total Occ.": 10,
            "Arr. Rooms": 1,
            "Dep. Rooms": 0,
            "Room Revenue": 377,
            "Average Rate": 38,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 11,
          },
          {
            date: "03-Jul-2020",
            "Total Occ.": 4,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 101,
            "Average Rate": 25,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 4,
          },
          {
            date: "04-Jul-2020",
            "Total Occ.": 11,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 101,
            "Average Rate": 9,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 11,
          },
          {
            date: "05-Jul-2020",
            "Total Occ.": 6,
            "Arr. Rooms": 1,
            "Dep. Rooms": 0,
            "Room Revenue": 214,
            "Average Rate": 43,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 6,
          },
          {
            date: "06-Jul-2020",
            "Total Occ.": 6,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 214,
            "Average Rate": 43,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 6,
          },
          {
            date: "07-Jul-2020",
            "Total Occ.": 10,
            "Arr. Rooms": 2,
            "Dep. Rooms": 0,
            "Room Revenue": 306,
            "Average Rate": 44,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 10,
          },
          {
            date: "08-Jul-2020",
            "Total Occ.": 21,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 961,
            "Average Rate": 51,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 21,
          },
          {
            date: "09-Jul-2020",
            "Total Occ.": 7,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 161,
            "Average Rate": 32,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 7,
          },
          {
            date: "10-Jul-2020",
            "Total Occ.": 7,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 161,
            "Average Rate": 32,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 7,
          },
          {
            date: "11-Jul-2020",
            "Total Occ.": 12,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 372,
            "Average Rate": 37,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 12,
          },
          {
            date: "12-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 2,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
          {
            date: "13-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
          {
            date: "14-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
          {
            date: "15-Jul-2020",
            "Total Occ.": 28,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1342,
            "Average Rate": 48,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 28,
          },
          {
            date: "16-Jul-2020",
            "Total Occ.": 23,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 1335,
            "Average Rate": 58,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 23,
          },
          {
            date: "17-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
          {
            date: "18-Jul-2020",
            "Total Occ.": 8,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 280,
            "Average Rate": 35,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 8,
          },
          {
            date: "19-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
          {
            date: "20-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
          {
            date: "21-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
          {
            date: "22-Jul-2020",
            "Total Occ.": 16,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 892,
            "Average Rate": 56,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 16,
          },
          {
            date: "23-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
          {
            date: "24-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
          {
            date: "25-Jul-2020",
            "Total Occ.": 8,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 280,
            "Average Rate": 35,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 8,
          },
          {
            date: "26-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
          {
            date: "27-Jul-2020",
            "Total Occ.": 106,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 12945,
            "Average Rate": 122,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 106,
          },
          {
            date: "28-Jul-2020",
            "Total Occ.": 106,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 12945,
            "Average Rate": 122,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 106,
          },
          {
            date: "29-Jul-2020",
            "Total Occ.": 121,
            "Arr. Rooms": 1,
            "Dep. Rooms": 0,
            "Room Revenue": 13801,
            "Average Rate": 115,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 121,
          },
          {
            date: "30-Jul-2020",
            "Total Occ.": 106,
            "Arr. Rooms": 0,
            "Dep. Rooms": 1,
            "Room Revenue": 12945,
            "Average Rate": 122,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 106,
          },
          {
            date: "31-Jul-2020",
            "Total Occ.": 3,
            "Arr. Rooms": 0,
            "Dep. Rooms": 0,
            "Room Revenue": 69,
            "Average Rate": 23,
            "Day Use Rooms": 0,
            "No Show Rooms": 0,
            "Adl. & Chl.": 3,
          },
        ],
      },
    ],
  },
  {
    periodDetail: [
      {
        title: "this month",
        period: "01-Feb-2020 - 29-Feb-2020",
        fromdate: "01-Feb-2020",
        todate: "29-Feb-2020",
      },
      {
        title: "3 months",
        period: "01-Feb-2020 - 30-Apr-2020",
        fromdate: "01-Feb-2020",
        todate: "30-Apr-2020",
      },
      {
        title: "6 months",
        period: "01-Feb-2020 - 31-Jul-2020",
        fromdate: "01-Feb-2020",
        todate: "31-Jul-2020",
      },
    ],
  },
];

function getHotelData(sectionName: string) {
  const sectionData: any = HotelData.find(
    (item) => Object.keys(item)[0] === sectionName
  );

  return sectionData ? sectionData[sectionName] : null;
}

export const actualData = getHotelData("actualData");
export const reservationForecastMonth = getHotelData(
  "reservationForecastMonth"
);
export const periodDetail = getHotelData("periodDetail");
